name: Auto-update Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - "*.md"

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip changelog]')"
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate changelog entry from commits
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
          outputFile: "TEMP_CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          # Get the version from the latest commit
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "Unreleased")
          DATE=$(date +%Y-%m-%d)
          
          # Create new changelog entry
          echo "## [$VERSION] - $DATE" > NEW_ENTRY.md
          echo "" >> NEW_ENTRY.md
          cat TEMP_CHANGELOG.md >> NEW_ENTRY.md
          echo "" >> NEW_ENTRY.md
          
          # Insert into existing changelog
          sed -i '/# Changelog/r NEW_ENTRY.md' CHANGELOG.md
          
          # Clean up
          rm TEMP_CHANGELOG.md NEW_ENTRY.md

      - name: Commit updated changelog
        run: |
          git config --local user.email "mike@corcra.dev"
          git config --local user.name "NoobTaco"
          git add CHANGELOG.md
          git commit -m "📝 Auto-update changelog [skip ci]" || exit 0
          git push
