name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - "*.md"
      - ".luacheckrc"
      - "Makefile"
      - "check-lua.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
