name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop-*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

  package-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test packaging (no upload)
        uses: BigWigsMods/packager@v2
        with:
          args: -d -z  # -d = no upload, -z = no zip (faster)

      - name: Test full package creation
        if: startsWith(github.ref, 'refs/heads/develop-')
        uses: BigWigsMods/packager@v2
        with:
          args: -d  # Creates zip but doesn't upload

      - name: Upload package as artifact (dev branches only)
        if: startsWith(github.ref, 'refs/heads/develop-')
        uses: actions/upload-artifact@v4
        with:
          name: NoobTacoUI-Media-${{ github.ref_name }}
          path: .release/*.zip
          retention-days: 7