name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop-*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@v1
        with:
          args: -q --ignore 113 631 211 212 112 311

  package:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/develop-')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and test
        uses: BigWigsMods/packager@v2
        with:
          args: -d -z