name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label-issues:
    runs-on: ubuntu-latest
    
    permissions:
      # Required for all workflows
      issues: write
      # Only required for workflows in private repositories
      actions: read
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yaml
      
      - name: Set labels based on WoW version
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: wow_version
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
