name: Release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to package for testing'
        required: true
        default: 'main'
        type: string

# Required for creating GitHub releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # On manual runs, checkout the branch from the input. On tag pushes, checkout the tag.
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Create changelog for packager
        run: awk '/^## \[[0-9.]+\]/{c++; if(c==2) exit} c>0' CHANGELOG.md > .changelog

      - name: Package and release (on tag push)
        if: github.event_name == 'push'
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Package for testing (on manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: BigWigsMods/packager@v2
        with:
          args: -d -g alpha # -d=no upload, -g alpha=create alpha package
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test package as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: NoobTacoUI-Media-Test-Package-${{ github.event.inputs.branch }}
          path: .release/*.zip
          retention-days: 7
          if-no-files-found: error