name: Release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to package for testing'
        required: true
        default: 'main'
        type: string

# Required for creating GitHub releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # On manual runs, checkout the branch from the input. On tag pushes, checkout the tag.
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Create changelog for packager
        run: awk '/^## \[[0-9.]+\]/{c++; if(c==2) exit} c>0' CHANGELOG.md > .changelog

      - name: Package and release (on tag push)
        if: github.event_name == 'push'
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Package for testing (on manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: BigWigsMods/packager@v2
        with:
          args: -d # Don't upload to external sites
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Preserve artifacts before cleanup
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "=== Copying artifacts before any cleanup ==="
          mkdir -p ./artifacts
          
          # Copy the zip file specifically
          if [ -d ".release" ]; then
            echo "Found .release directory, copying zip files..."
            find .release -name "*.zip" -exec cp {} ./artifacts/ \;
            echo "Contents of .release directory:"
            ls -la .release/
            
            # Look for any changelog files the packager might have created
            echo "Looking for changelog files in .release:"
            find .release -name "*change*" -o -name "*CHANGE*" -o -name "*.md" -o -name "*.txt" | head -10
          else
            echo "No .release directory found"
          fi
          
          # Copy our raw changelog file for comparison
          if [ -f ".changelog" ]; then
            echo "Found .changelog file, copying..."
            cp .changelog ./artifacts/raw-changelog.txt
            echo "Raw changelog copied as raw-changelog.txt"
          else
            echo "No .changelog file found"
          fi
          
          # Also check what's inside the zip file structure
          if ls ./artifacts/*.zip 1> /dev/null 2>&1; then
            echo "=== Examining zip file contents ==="
            for zipfile in ./artifacts/*.zip; do
              if [ -f "$zipfile" ]; then
                echo "Contents of $zipfile:"
                unzip -l "$zipfile" | head -20
                
                # Try to extract any changelog files from the zip
                echo "Extracting potential changelog files from zip:"
                unzip -j "$zipfile" "*/CHANGELOG.md" -d ./artifacts/ 2>/dev/null || echo "No CHANGELOG.md in zip"
                unzip -j "$zipfile" "*/changelog.txt" -d ./artifacts/ 2>/dev/null || echo "No changelog.txt in zip"
                unzip -j "$zipfile" "*/*change*" -d ./artifacts/ 2>/dev/null || echo "No other changelog files in zip"
                break
              fi
            done
          fi
          
          echo "=== Final artifacts directory contents ==="
          ls -la ./artifacts/

      - name: Show test results
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "=== Test Package Created Successfully ==="
          echo "Zip file:"
          find .release -name "*.zip" -ls 2>/dev/null || echo "No zip files found in .release"
          find ./artifacts -name "*.zip" -ls 2>/dev/null || echo "No zip files found in ./artifacts"
          echo ""
          echo "=== Changelog Content ==="
          echo "Extracted changelog (.changelog file):"
          cat .changelog 2>/dev/null || cat ./artifacts/.changelog 2>/dev/null || echo "No changelog found"
          echo ""
          echo "=== Directory contents before upload ==="
          ls -la .release/ 2>/dev/null || echo "No .release directory found"
          ls -la ./artifacts/ 2>/dev/null || echo "No ./artifacts directory found"
          echo ""
          echo "=== Current working directory ==="
          pwd
          ls -la
          echo ""
          echo "=== Test completed - package would be ready for release ==="

      - name: Upload test package as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: NoobTacoUI-Media-Test-Package
          path: ./artifacts/
          retention-days: 7